### ISSUE TITLE
Might not work on php 5.2

### ISSUE THREAD

**Issue by Cipa** [jeroenwtf/codeigniter-extended-rules#3]
Hi,

It would be nice if the code would work on php 5.2. For example anonymous functions don't work on php 5.2

**Comment by Patroklo** [comment]
Uh, it's going to be hard to check this thing in php 5.2. I'll get rid of the anonymous function because it's totally disposable. But, are you aware of anything more that coul crash in that php version?

**Comment by Cipa** [comment]
Hi,

I think the anon function and date_parse_from_format are the 2 things that need to be replaced.

The problem is that I could not find a good date_parse_from_format function for php5.2 so I implemented a mysql date check that works for me.

The rest seems fine

Thank you

**Comment by Cipa** [comment]
Also not really a bug but: $_standar_date_format is missing a 'd'; should be $_standard_date_format I belive

**Comment by Patroklo** [comment]
Cool, I have just seen a date_parte_format equivalent and with very little changes can be used without problems, i'll add it for 5.2 or below, for now I have changed the closure and changed the $_standard... I'll check for bugs or problems and when I'm done I'll upload the new version. Thanks for your help!

**Comment by Cipa** [comment]
Let me know when it's done. I'll test as well
Thnak you

**Comment by Patroklo** [comment]
Just uploaded the new version, you can check it if you want. Should work for 5.2 fine now.

**Comment by Cipa** [comment]
This is what I get and I am not sure what would be causing it. 

Here's my validation rule. The validation fails and I get an error

```
$this->form_validation->set_rules('dob', 'Date of Birth', 'required|valid_date[YYYY-MM-DD]');
```

Here's the error

```
A PHP Error was encountered

Severity: Warning

Message: preg_match() [function.preg-match]: Compilation failed: two named subpatterns have the same name at offset 24

Filename: libraries/MY_Form_validation.php

Line Number: 915
```

**Comment by Patroklo** [comment]
That's because the rules of date in php of the validation should be Y-M-D (there's not such thing as YYYY in date()) and it should look like:  (2012-Jan-Mon , strange date, ceirtanlly :P ) 
Check it out here: http://www.php.net/manual/es/function.date.php because I think that you want a simple "Y-m-d"

**Comment by Patroklo** [comment]
I'm thinking that I should describe this particular behaviour, yes...

**Comment by Cipa** [comment]
I think that Y m d is correct. I got stuck with the mysql format. Thanks
